version: "3"

services:

  mongo:
    image: 'tutum/mongodb:3.2'
    container_name: mongo
    environment:
      - MONGODB_PASS=password
    ports:
      # this is port mapping from host to container.
      # if we dont map the host, it wont be available outside completely isolated for security.
      # TODO: remove outside port mapping
      - '27017:27017'

  lucidsentry:
    image: 'lucidprogrammer/sentry:latest'
    container_name: lucidsentry
    # lets dont keep a state on the container.
    depends_on:
      - mongo
    # whenever there is a new image, autoredeploy
    command: node /meteor-build/bundle/main.js
    entrypoint: node /meteor-build/bundle/main.js
    environment:
      - 'PORT=3000'
      - 'MONGO_URL=mongodb://admin:password@mongo:27017'
      - 'ROOT_URL=http://lucidprogrammer.info'

  nginx:
    image: lucidprogrammer/nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - lucidsentry
    ports:
      - 80:80
    volumes:
      # proxies
      - "./site.nginx.json:/etc/nginx/conf.d/proxies/proxies.json:ro"   
